data = readmatrix('Dulieu1.3.txt');
ax = data(:,1); ay = data(:,2); az = data(:,3);
gx = data(:,4); gy = data(:,5); gz = data(:,6);
off_ax = mean(ax) - 0; 
off_ay = mean(ay) - 0; 
off_az = mean(az) - 1.0; 
off_gx = mean(gx) - 0; 
off_gy = mean(gy) - 0; 
off_gz = mean(gz) - 0;
std_ax = std(ax); std_ay = std(ay); std_az = std(az);
std_gx = std(gx); std_gy = std(gy); std_gz = std(gz);
fprintf('--- BẢNG ĐÁNH GIÁ ĐẶC TÍNH TĨNH (PHẦN 1.3) ---\n');
fprintf('Trục\tZero-offset (Bias)\tNoise (STD)\n');
fprintf('Ax\t%.4f g\t\t%.4f g\n', off_ax, std_ax);
fprintf('Ay\t%.4f g\t\t%.4f g\n', off_ay, std_ay);
fprintf('Az\t%.4f g\t\t%.4f g\n', off_az, std_az);
fprintf('Gx\t%.4f °/s\t\t%.4f °/s\n', off_gx, std_gx);
fprintf('Gy\t%.4f °/s\t\t%.4f °/s\n', off_gy, std_gy);
fprintf('Gz\t%.4f °/s\t\t%.4f °/s\n', off_gz, std_gz);