calibData = readmatrix('data_phan1_calibrated.txt');
validCalibData = calibData(1:500, 1:6);

ax_calib = validCalibData(:, 1);
ay_calib = validCalibData(:, 2);
az_calib = validCalibData(:, 3);
gx_calib = validCalibData(:, 4);
gy_calib = validCalibData(:, 5);
gz_calib = validCalibData(:, 6);
f = figure('Position', [100, 100, 800, 600]);
subplot(2,1,1);
plot(ax_calib, 'LineWidth', 1.2); hold on;
plot(ay_calib, 'LineWidth', 1.2);
plot(az_calib, 'LineWidth', 1.2);
title('Calibrated Accelerometer Data (g)');
ylabel('Acceleration (g)');
legend('Ax (Ve 0)', 'Ay (Ve 0)', 'Az (khoang 1g)', 'Location', 'best');
grid on;
hold off;
subplot(2,1,2);
plot(gx_calib, 'LineWidth', 1.2); hold on;
plot(gy_calib, 'LineWidth', 1.2);
plot(gz_calib, 'LineWidth', 1.2);
title('Calibrated Gyroscope Data (deg/s)');
xlabel('Sample');
ylabel('Angular Velocity (deg/s)');
legend('Gx (Ve 0)', 'Gy (Ve 0)', 'Gz (Ve 0)', 'Location', 'best');
grid on;
hold off;

saveas(f, 'DoThi_Calibrated_Phan1.png');